### PR TITLE
Adding goal to build slug only

### PR DESCRIPTION
**Pull request by abrauner**
To separate slug-creation and slug-deployment I added a new maven goal. There should be nearly no new code as I refactored the existing solution. Advantage of this third goal would be the possibility to create the slug once and re-use it in several stages without creating it again every time you want to deploy. This already includes the refactoring of #7 .

### CODE REVIEW

**Comment by abrauner** [comment]
Travis seems to fail with authentication errors. 
```
Enter your Heroku credentials.
Email: Password (typing will be hidden): 
Authentication failed.
```

**Comment by jkutner** [comment]
I think it's good to have a `create-slug` goal, but I'm not sure I want to cause the `deploy` goals to reuse an existing slug -- this could lead to unexpected behavior for people who are already using the plugin, or are unfamiliar with how it works under the hood. I prefer having it execute cleanly every time.

What do you think about introducing both `create-slug` and `deploy-slug` goals, and leaving the other goals the same? 

BTW, I'm going to introduce caching of the JDK, so it does not have to be downloaded every time, but that's a separate change.

**Comment by abrauner** [comment]
I think people using maven know that they have to clean up their target folder when they want to have a new built. And only when the build-artifacts change it makes sense build a new slug. This way it should be fine to change this. 

To avoid problems a two-step change could be an option. Maybe the users could be warned in the next version to change their builds and in the version after that the behavior could be changed. 

For the first-step I would update this pull-request with the deploy-slug goal so we have separated this.

**Comment by jkutner** [comment]
I'll add the `deploy-slug` goal. You can leave this PR as is, and I'll merge it shortly. Thanks for the code!

**Comment by abrauner** [comment]
There might be one thing I would update if its ok. There is another file-extension set in Tar.java in line 98. This is obsolet due my change and the concatination of .tgz needs to be removed. 
So Line 98 would be: 
```File outputFile = new File(outputDir, (archiveBasename));```

**Comment by jkutner** [comment]
Yea, feel free to update this. I haven't started on it yet.

**Comment by jkutner** [comment]
For some reason, it's not recognizing this as merged. I merged it manual here: https://github.com/heroku/heroku-maven-plugin/commit/75000094fe3ff2609b06b4be3bca957150a2933a

I also did some rework on on it to add the `deploy-slug` goal. I've kept both of these goals quite in the documentation though. I don't want it to confuse people, and cause them to think that it's the preferred path (I'd like to keep most people on the full deploy every time). But if I get enough people requesting it, I'll document it better.

Thanks for submitting this!

**Pull request closed without merging**
